### ISSUE TITLE
not smooth when changing `playbackSpeed` of the video

### ISSUE THREAD

**Issue by DieGlueckswurst** [timcreatedit/smooth_video_progress#2]
If I change the vidoes `playbackSpeed` it's clunky and hops back or forth depending on the speed. 

![RPReplay_Final1675415171](https://user-images.githubusercontent.com/40027124/216559692-0464e34c-8f9c-4ca5-a86f-8753b34e3a02.gif)

**Comment by timcreatedit** [comment]
Ah that's a great find and should be fairly easy to fix! If you look at the code, there's a couple magic numbers in there that would need to be divided by the current playback speed probably.
I'll see if I have time to fix it later today, otherwise you're welcome to open a PR! :)
Thanks for using the library and submitting such a well documented issue!

**Comment by DieGlueckswurst** [comment]
I was wondering what these numbers are for :D thanks! let me know if you were able to fix it. Everything else is working perfectly smooth :)

**Comment by timcreatedit** [comment]
I think I'm actually wrong about having to change these numbers tbh, it's been I while since I've worked on this package. I think the problem might actually be the AnimationController that needs to be adjusted to play at the desired speed haha. Glad to hear everything else works though!

**Comment by DieGlueckswurst** [comment]
do you think you can fix it? I tried some things but nothing worked

**Comment by timcreatedit** [comment]
I wrote a quick fix in #3 could you maybe check it out and see if you're satisfied with that solution for now? :)

**Comment by DieGlueckswurst** [comment]
a bit clunky when changing the speed but animating smoothly :) its fine for me, thanks!
